name: Snyk Maven Dependency Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Update to Java 17
          distribution: 'temurin'  

      - name: Build with Maven
        run: mvn -B package -DskipTests=true --file pom.xml


      - name: Run Snyk Maven Dependency Scan
        uses: snyk/actions@0.4.0  # Ensure this version is valid
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test --all-projects --file=pom.xml


