name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: SonarQube Scan
        env:
          SONAR_TOKEN:"squ_dc6c35ac72a1d8e64ef23026585e581b122b7446"
        run: mvn sonar:sonar -Dsonar.projectKey=your_project_key -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.host.url=http://your-sonarqube-server:9000

